"use client";
// Wrapper around the xchannuity-core WASM module (generated by `wasm-pack build`
// into ../wasm-pkg). `init` follows the wasm-pack `--target web` convention.
import init, {
  stream_puzzle_hash_hex,
  protocol_fee_bps,
  annuity_inner_puzzle_hash,
  annuity_cat_puzzle_hash,
  standard_puzzle_hash,
  cat_puzzle_hash,
  coin_id,
  claimable_now,
  aggregate_signatures,
  supported_assets,
  address_to_puzzle_hash,
  puzzle_hash_to_address,
  build_create_annuity,
  build_claim,
  build_clawback,
  build_transfer,
  build_open_offer,
  build_take_from_offer,
  inspect_offer,
  encode_offer,
  discover_from_parent,
} from "@wasm";

let _ready: Promise<void> | null = null;

export function ensureWasm(): Promise<void> {
  if (typeof window === "undefined") return Promise.reject(new Error("browser only"));
  if (!_ready) _ready = init().then(() => undefined);
  return _ready;
}

export {
  stream_puzzle_hash_hex,
  protocol_fee_bps,
  annuity_inner_puzzle_hash,
  annuity_cat_puzzle_hash,
  standard_puzzle_hash,
  cat_puzzle_hash,
  coin_id,
  claimable_now,
  aggregate_signatures,
  supported_assets,
  address_to_puzzle_hash,
  puzzle_hash_to_address,
  build_create_annuity,
  build_claim,
  build_clawback,
  build_transfer,
  build_open_offer,
  build_take_from_offer,
  inspect_offer,
  encode_offer,
  discover_from_parent,
};
